name: main
on:
  workflow_dispatch:
    inputs:
      type:
        description: 'The version to bump to. Either a semver string, patch, minor, major, prepatch, preminor, premajor, prerelease, or from-git'
        required: true
        default: 'patch'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - run: |
          git config user.email "github-actions[bot]@example.com"
          git config user.name "github-actions [bot]"
          npm version ${{ github.event.inputs.type }}
      - run: |
          git push
          git push --tags
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
